export default function CompliancePage() {
  const base = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:8000";
  const pdf = `${base}/compliance/audit_report.pdf`;
  return (
    <div className="card" style={{display:"grid", gap:12}}>
      <h1>Compliance</h1>
      <p>Open the audit trail report as a PDF generated by the backend.</p>
      <a className="btn" href={pdf} target="_blank">Open Audit Report (PDF)</a>
    </div>
  );
}
