// src/app/compliance/page.tsx
const BASE = process.env.NEXT_PUBLIC_API_BASE || "https://toct-backend.onrender.com";

export default function CompliancePage() {
  return (
    <div className="section">
      <div className="card">
        <h1>Compliance • Audit Report</h1>
        <p className="muted">Download a sample audit report generated by the backend.</p>
        <a className="btn" href={`${BASE}/compliance/audit_report.pdf`} target="_blank" rel="noopener">
          Open Audit Report (PDF)
        </a>
      </div>
    </div>
  );
}
