version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: toct
      POSTGRES_PASSWORD: toctpwd
      POSTGRES_DB: toct
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U toct -d toct"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://toct:toctpwd@db:5432/toct
      REDIS_URL: redis://redis:6379/0
      ALLOW_ORIGINS: http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports: ["8000:8000"]

  worker:
    build: ./backend
    command: ["bash","-lc","python -m app.worker"]
    environment:
      DATABASE_URL: postgresql+psycopg://toct:toctpwd@db:5432/toct
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    depends_on: [backend]
    ports: ["3000:3000"]
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000

volumes:
  dbdata:
